### ISSUE TITLE
code review

### ISSUE THREAD

**Issue by codegyeon** [junyoung93/spring-week1-hw#1]

**Comment by codegyeon** [comment]
![스크린샷 2023-06-28 오전 9 12 55](https://github.com/junyoung93/spring-week1-hw/assets/99954094/8b66fccc-c370-481d-9957-6ad207a65b4f)
Restpull 한 설계가 무엇인지 보셨으면 좋겠습니다!

**Comment by codegyeon** [comment]
![스크린샷 2023-06-28 오전 9 24 23](https://github.com/junyoung93/spring-week1-hw/assets/99954094/ad9c325a-77e8-4b6e-b8f9-528563255363)
Respons 에 password 같은 보안에  예민한 부분은 응답으로 안보내는것이 좋을것 같습니다!

**Comment by codegyeon** [comment]
![스크린샷 2023-06-28 오전 9 48 18](https://github.com/junyoung93/spring-week1-hw/assets/99954094/193e6475-38ff-4b3e-a53c-3262053b7562)
데이터베이스 설정 정보도 예민할 수 있는 문제가 될것같습니다. propertice 설정을 숨기는 방법이 있어요. 그걸 한번 찾아보심 좋을것같습니당

**Comment by Nhahan** [comment]
질문이 따로 없는 이유가 이미 codegyeon님이 리뷰를 확실하게 해주고 계셨군요! 제가 codegyeon님 이슈에 남긴 것들 모두 (혹은 이슈에 달린 코드에) 코멘트 혹은 리뷰를 달아놓았으니 같이 확인해보셔도 좋을 것 같아요. 아마 옛날 코드들이라 대부분은 고쳐진거 같긴 했습니다!
